[package]
name = "caltrack"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
home = "0.5.3"
ansi_term ="0.12"
